services:
  - type: web
    name: kartr-influencer-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SESSION_SECRET
        generateValue: true
      - key: AUTH0_DOMAIN
        sync: false
      - key: AUTH0_CLIENT_ID
        sync: false
      - key: AUTH0_CLIENT_SECRET
        sync: false
      - key: AUTH0_API_AUDIENCE
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
